name: GitHub Actions Demo
on: [push]
jobs:
  Passive-Balancer-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: make
      - run: test-integration
